# Generated by Django 3.2.23 on 2023-12-17 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='disease_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100)),
                ('remedy', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('specilization', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacy_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='prescription_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField()),
                ('date', models.DateField()),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.booking_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='symptom_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.disease_table')),
            ],
        ),
        migrations.CreateModel(
            name='shedule_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('fromtime', models.CharField(max_length=100)),
                ('totime', models.CharField(max_length=100)),
                ('DOCTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.doctor_table')),
            ],
        ),
        migrations.CreateModel(
            name='request_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('PHARMACY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.pharmacy_table')),
                ('PRESCRIPTION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.prescription_table')),
            ],
        ),
        migrations.CreateModel(
            name='medicine_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=100)),
                ('PHARMACY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.pharmacy_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('date', models.DateField()),
                ('DOCTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.doctor_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.user_table')),
            ],
        ),
        migrations.AddField(
            model_name='doctor_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.login_table'),
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.user_table')),
            ],
        ),
        migrations.AddField(
            model_name='booking_table',
            name='SHEDULE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.shedule_table'),
        ),
        migrations.AddField(
            model_name='booking_table',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.user_table'),
        ),
        migrations.CreateModel(
            name='bill_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('MEDICINE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.medicine_table')),
                ('REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.request_table')),
            ],
        ),
    ]
