# Generated by Django 3.2.23 on 2023-12-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_managementapp', '0002_alter_prescription_table_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill_table',
            name='MEDICINE',
        ),
        migrations.RemoveField(
            model_name='bill_table',
            name='REQUEST',
        ),
        migrations.RemoveField(
            model_name='bill_table',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bill_table',
            name='quantity',
        ),
        migrations.AddField(
            model_name='bill_table',
            name='PHARMACY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.pharmacy_table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill_table',
            name='Status',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill_table',
            name='Total',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill_table',
            name='prescription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.prescription_table'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='bill_items_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=600)),
                ('MEDICINE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.medicine_table')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_managementapp.bill_table')),
            ],
        ),
    ]
