# Generated by Django 3.2.24 on 2024-03-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_managementapp', '0006_auto_20231222_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_table',
            name='qualification',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctor_table',
            name='specilization',
            field=models.TextField(),
        ),
    ]
