# Generated by Django 3.2.24 on 2024-03-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_managementapp', '0007_auto_20240321_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule_table',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shedule_table',
            name='fromtime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shedule_table',
            name='totime',
            field=models.TimeField(),
        ),
    ]
